version: '3'

services:
  webserver:
    container_name: webserver
    build: ./images/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./images/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    links:
      - application
      - redis

  application:
    container_name: application
    build: ./images/application
    ports:
      - "9500:9000"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    links:
      - database
    environment:
      - DB_PORT=3306
      - DB_HOST=database

  database:
    container_name: database
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker-database
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6500:6379"

